name: CI

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ [ macos-latest ], [ ubuntu-latest ] ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Checkout Gradle Build Cache
        if: ${{ steps.self_hosted.outputs.FLAG != 'self-hosted' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/wrapper/dists/**/gradle*.zip
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Debug
        run: ./gradlew build -x test

      - name: Build Release App
        run: |
          ./gradlew package

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "distributable ${{ matrix.os }}"
          if-no-files-found: ignore
          path: |
            build/**/*.dmg
            build/**/*.deb
